### PR TITLE
Replace outdated pgdump image with tracable change files.

### PR DESCRIPTION
**Pull request by jeremyh**
The current pgdump image is out of date. These commits replace it, as well as allowing future updates to be tracked more easily and transparently in plain text.

Future changes can be made by adding a new SQL file to the directory. (eg. `v5__wofs.sql`), and [Flyway](http://flywaydb.org/) can be used to track changes applied in each environment. See the README file in the `databases/` folder for more information.

The SQL files here were derived from current Landsat and Modis production databases, to provide a single schema consistent across all environments.

### CODE REVIEW

**Comment by jeremyh** [comment]
For reference:

- `v1` and `v2` create an schema to the current Landsat DB.
- `v3` (constraint adjustment) Adds my own schema updates
- `v4` Adds changes from the current Modis production DB.
- `v5` Adds WOfS definitions.

**Comment by woodcockr** [comment]
This looks like a great addition to the code base. As one of the representatives of the AGDC pull request approval team I support this pull request
+1

**Comment by woodcockr** [comment]
opps hit the wrong button and accidentally closed it. No harm done though.

**Comment by petewa** [comment]
I fully support this as this will allow changes to the database schema to be tracked with ordered changes to bring the database schema up to date.

I will +1 this pull request, pending some minor changes to the MODIS scripts.

**Comment by alex-ip** [comment]
+1 from me, too.
We might need to get Jeremy to give a quick presentation on Flyway and how to manage and apply the changes. This work will be very relevant to Gareth's work on managed replication.

**Comment by wenjunwu** [comment]
agreed!

**Pull request merged**
